# tensorflow

In [1]:
import tensorflow as tf

In [4]:
# 암묵적 타입 변수 생성
x = tf.Variable(123)
tf.print(x)

y = tf.Variable(x + 100)
tf.print(y)

123
223


In [5]:
# 명시적 타입 변수 생성
x = tf.Variable(123, dtype = tf.float32)
tf.print(x)

123


In [6]:
import numpy as np

In [8]:
# rank 0 -> scalar
a = 100
ts1 = np.array(a)
print(ts1.shape)
ts1

()


array(100)

In [10]:
# rank 1 -> vector
b = [1,2,3]
ts2 = np.array(b)
print(ts2.shape)
ts2

(3,)


array([1, 2, 3])

In [11]:
# rank 2 -> matrix
c = [[10,20,30],[100,200,300]]
ts3 = np.array(c)
print(ts3.shape)
ts3

(2, 3)


array([[ 10,  20,  30],
       [100, 200, 300]])

In [12]:
# rank 3 -> tensor
d = [[[-1,-2,-3], [1,2,3]], [[-1,0,1],[1,0,-1]]]
ts4 = np.array(d)
print(ts4.shape)
ts4

(2, 2, 3)


array([[[-1, -2, -3],
        [ 1,  2,  3]],

       [[-1,  0,  1],
        [ 1,  0, -1]]])

### 계산그래프

In [13]:
# 명시적타입 노드
node1 = tf.constant(3.0, dtype = tf.float32, name='hello')
print(node1)
tf.print(node1)

tf.Tensor(3.0, shape=(), dtype=float32)
3


In [14]:
# 암묵적타입 노드
node2 = tf.constant(4.0, name = 'world')
print(node2)
tf.print(node2)

tf.Tensor(4.0, shape=(), dtype=float32)
4


In [16]:
node3 = tf.add(node1, node2)
print(node3)
tf.print(node3)

tf.Tensor(7.0, shape=(), dtype=float32)
7


# 01. 균등 분포 난수

일반적으로 각 이벤트의 결과값을 알 수 없는 경우 미래에 발생할 이벤트의 결과값 $x$가 각 예상되는 범위별로 균등한 확률로 일어날 것이라고 예상될 때 사용.

## 1) 균등 분포 난수의 사용 예

### 주사위에 대한 확률

- 200번을 던지고 201번째  주사위를 던진다고 했을 때 201번째 결과값은 앞의 1에서 200번까지 결과값에 영향을 받지 않는다.
- 201번째 결과값이 1,2,3,4,5,6 각각의 결과값으로 나올 확률은 6분의 1이며 이는 앞의 1~200번째 결과값에 영향을 받아 줄어들거나 늘어나지 않는다는 것이다.
- 이처럼 미래 결과값이 경험적으로 알 수 없을 상황에서 사용하는 것이 균등분포이다.

## 2) 균등 분포 난수 실험

생성되는 배열의 각 원소들은 **서로 아무런 연관이 없는 값**들이다.

In [18]:
# 스칼라 형태
uni_rnd1 = tf.random.uniform(shape=[], minval = 0, maxval = 100, dtype=tf.int32)
tf.print(uni_rnd1)

97


In [19]:
# 백터 형태
uni_rnd2 = tf.random.uniform(shape=[5], minval=0, maxval=100, dtype=tf.int32)
tf.print(uni_rnd2)

[19 24 60 10 99]


In [20]:
# 행렬 형태
uni_rnd3 = tf.random.uniform(shape=[2,3], minval=0, maxval=100, dtype=tf.int32)
tf.print(uni_rnd3)

[[21 35 72]
 [31 31 30]]


In [21]:
# 텐서 형태
uni_rnd4 = tf.random.uniform(shape=[2,3,4], minval=0, maxval=100, dtype=tf.int32)
tf.print(uni_rnd4)

[[[75 98 53 56]
  [61 65 35 35]
  [44 95 30 19]]

 [[97 35 97 54]
  [14 20 69 18]
  [90 12 20 75]]]


## 3) 렌덤값을 갖는 행렬 곱 예시

In [22]:
# 랜덤값을 갖는 3행2열의 행렬을 변수 x로 정의

x = tf.Variable(tf.random.uniform([3,2]))
tf.print(x)

[[0.168972492 0.520079494]
 [0.69362545 0.729974151]
 [0.467871428 0.794957161]]


In [23]:
# 랜덤값을 갖는 2행1열의 행렬을 변수 y로 정의
y = tf.Variable(tf.random.uniform([2,1]))
tf.print(y)

[[0.339716792]
 [0.744208]]


In [24]:
# 행렬곱 연산
expr = tf.matmul(x,y)
tf.print(expr)

[[0.44445011]
 [0.778888822]
 [0.750557244]]


# 02. 정규 분포 난수

정규분포란 과거의 축적된 경험적 데이타를 이미 보유하고 있는 상태에서 이용하여 미래에 발생할 결과값 $x$의 각 예상되는 범위별로 발생될 확률을 어느정도 추정할 수 있을 때 사용

## 1) 정규 분포 난수의 사용 예

### 매장의 매출액 예측

- 이전 3개월의 매출이 2천만원, 2천백만원, 2천2백원 발생한 경우 평균이나 범위에 대한 예측이 가능하다.
- **`평균`에 대한 예측** → 이번달 매출은 과거 3개월의 매출평균인 2천백만원으로 예측.
- **`범위`에 대한 예측** → 최소 2천만원 ~  최대 2천2백만원까지 매출이 발생할 수 있다는 예상이 가능함.

## 2) 정규 분포 난수 실험

정규 분포 난수를 생성할 때는 평균(`mean`)과 표준편차(`stddev`)를 지정해야 한다.

In [26]:
# 스칼라 형태의 정규 분포 난수

normal_rnd1 = tf.random.normal(shape=[], mean=0.0, stddev=1.0)
tf.print(normal_rnd1)

-0.427608


In [27]:
# 벡터 형태의 정규 분포 난수

normal_rnd2 = tf.random.normal(shape=[5], mean=0.0, stddev=1.0)
tf.print(normal_rnd2)

[0.539380193 -0.979874313 -0.876616597 -0.885023236 0.0747114494]


In [29]:
# 행렬 형태의 정규 분포 난수

normal_rnd3 = tf.random.normal(shape=[2,3], mean=0.0, stddev=1.0)
tf.print(normal_rnd3)

[[-0.818370879 -1.72787797 0.624223113]
 [-2.18556547 0.323906064 -2.63690782]]


In [30]:
# 텐서 형태의 정규 분포 난수

normal_rnd4 = tf.random.normal(shape=[2,3,4], mean=0.0, stddev=1.0)
tf.print(normal_rnd4)

[[[0.522125065 -0.680715 1.79687464 0.490538329]
  [0.494646877 -0.571822286 -0.149716884 1.79880142]
  [-1.06935501 1.34277308 -1.48494351 0.102838553]]

 [[0.696822047 -0.492854625 -1.67485976 -0.491056114]
  [1.27685153 -0.962324321 -1.21202707 0.954417825]
  [0.388219953 0.180628195 0.336251825 -0.300854832]]]
