# Numpy

In [1]:
import numpy

# 배열 생성
arr = numpy.array([1,3,5,7,9])
print (arr)

[1 3 5 7 9]


배열의 크기와 원소 접근은 리스트와 동일

In [2]:
# 자료형이 다른것을 허용하지 않는다
# 더 범위가 큰 자료형으로 강제 형변환

arr3 = numpy.array([1, 2.4, 3, 4.6])
print(arr3)

[1.  2.4 3.  4.6]


## 다양한 초기화 방법

In [11]:
# 0~15전 까지 순차배열 생성
a = numpy.arange(15)
print(a)

# 100부터 115전까지
b = numpy.array(range(100,115))
print(b)

# 모든 원소가 0
c = numpy.zeros([3])
# c = numpy.zeros([3]. dtype='int') 정수형으로 만들때
print(c) # 기본실수

# 모든 원소가 1
d = numpy.ones([3])
# d = numpy.ones([3]. dtype='int') 정수형으로 만들때
print(d) #기본실수

# 원하는 수로 채우고 싶을 때
f = numpy.full([5], 7) # 채우고자 하는 수의 자료형을 따라감 (이 경우는 정수)
print(f)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[100 101 102 103 104 105 106 107 108 109 110 111 112 113 114]
[0. 0. 0.]
[1. 1. 1.]
[7 7 7 7 7]


## 기초 통계값 산출

In [14]:
grade = numpy.array([82,77,91,88])

# 원소의 합
s1 = numpy.sum(grade)
print(s1)

# 원소의 평균
s2 = numpy.average(grade)
print(s2)

# 최대, 최소값
s3 = numpy.max(grade)
s4 = numpy.min(grade)
print(s3, s4)

338
84.5
91 77


## 배열의 연산

In [16]:
# 사칙연산은 기본적으로 모든 원소에 대해 적용
new1 = grade + 2
print(new1) # grade = [82,77,91,88]

new2 = grade - 5
print(new2)

[84 79 93 90]
[77 72 86 83]


In [20]:
# 사이즈가 동일하다면 배열끼리의 사칙연산도 지원

arr1 = numpy.array([1,2,3,4,5])
arr2 = numpy.array([2,4,6,8,10])

# 여러가지 사칙연산
a = arr1 + arr2
print(a)

b = arr1 - arr2
print(b)

c = arr1 * arr2
print(c)

d = arr1 / arr2
print(d)

#numpy. add(), subtarct(), multiply(), divide() 함수도 존재

[ 3  6  9 12 15]
[-1 -2 -3 -4 -5]
[ 2  8 18 32 50]
[0.5 0.5 0.5 0.5 0.5]


## 인덱싱

### 기본적으로 리스트 튜플과 동일
다른점만 정리

## 조건부 인덱싱

In [25]:
import numpy as np

bool_array = np.array([True, False, True, False])
grade = np.array([82,77,91,88])

# -> 조건에 맞는 항목만 1차 배열로 추출
result1 = grade[bool_array]
print(result1)

# 아래 조건식에서는 배열의 이름을 그대로 사용한다.

# 특정 조건에 맞는 값 추출
result2 = grade[grade >= 80]
print(result2)

# logical_and와 logical_or를 이용한 조건부 추출
result3 = grade[np.logical_and(grade >= 80, grade <= 90)]
print(result3)

result4 = grade[np.logical_or(grade < 80, grade > 90)] 
print(result4)

[82 91]
[82 91 88]
[82 88]
[77 91]


## 2차원 배열

### 2차원 리스트를 numpy.array()안에 넣으면 된다.

In [29]:
grade = np.array([
    [98, 72, 80, 63],
    [88, 90, 80, 72],
    [92, 88, 82, 76]
])

# 배열 정보
print("차원크기: %d" % grade.ndim) # 배열의 차원을 리턴함

print( grade.shape ) # 각 차원의 원소수를 튜플로 표시 (3행 4열 이라는뜻)

print( grade.dtype ) # 원소의 타입

차원크기: 2
(3, 4)
int32


## 인덱싱 슬라이싱

[행, 열] 로 접근한다

In [31]:
# 슬라이싱
print(grade[1:3, 1:4]) # 1~3행전, 1~4열전 의 범위의 합집합을 출력

[[90 80 72]
 [88 82 76]]


## 기본 통계

In [40]:
s1 = np.sum(grade, axis = 0) # axis = 0은 열을 뜻한다 ( 각 열끼리 더함 )
print(type(s1)) # 연산결과도 array
print(s1)

s2 = np.sum(grade, axis = 1) # axis = 1은 행을 뜻한다 ( 각 행끼리 더함 )
print(type(s2)) # 연산결과도 array
print(s2)


# sum,average, min, max 모두 사용가능

<class 'numpy.ndarray'>
[278 250 242 211]
<class 'numpy.ndarray'>
[313 330 338]


## 논리값과 비교식을 이용한 조건부 인덱싱

In [45]:
bool_array = np.array([
    [True, False, True, False],
    [True, True, True, False],
    [True, True, True, False]
])


# 조건에 맞는 항목 추출 (1차원 배열)
result1 = grade[bool_array]
print(result1)

result2 = grade[grade >= 80]
print(result2)

# 논리식을 사용
result3 = grade[np.logical_and(grade >= 80, grade <= 90)]
print(result3)

result4 = grade[np.logical_or(grade < 80, grade > 90)]
print(result4)

[98 80 88 90 80 92 88 82]
[98 80 88 90 80 92 88 82]
[80 88 90 80 88 82]
[98 72 63 72 92 76]
